- name: Forward required ports
  iptables:
    chain: INPUT
    match: state
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    ctstate: NEW
    state: present
    comment: "{{ item.comment }}"
  become: yes
  with_items:
    - { port: 6379, protocol: tcp, comment: "Open port 6379 for Redis"}
    - { port: 3000, protocol: tcp, comment: "Open port 3000 for node"}
    - { port: 8080, protocol: tcp, comment: "Open port 8080 for Apache" }
    - { port: 5432, protocol: tcp, comment: "Open port 5432 for pgAdmin" }
    - { port: 445, protocol: tcp, comment: "Open port 445 for samba" }

#- name: Restart server to apply firewall rules
#  command: /sbin/shutdown -r
#  async: 0
#  poll: 0
#  ignore_errors: true
